version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: proje_postgres
    restart: always
    environment:
      POSTGRES_DB: proje_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_gizli_sifre123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: ghcr.io/erenalbayrakk04/projeapi:latest
    container_name: proje_api
    restart: always
    environment:
      DB_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: proje_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_gizli_sifre123
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    image: ghcr.io/erenalbayrakk04/projeapi-frontend:latest
    container_name: proje_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: